### PR TITLE
Fixed: Links to some MSS in Digital Bodleian

### PR DESCRIPTION
**Pull request by ahankinson**
The Digital Bodleian link pointed to a page in the middle of the book, and not to the object ID.

### CODE REVIEW

**Comment by andrew-morrison** [comment]
I think a lot of the links in the TEI files use URLs based on the ID of the first page, not the object ID for the entire manuscript. Does that make a difference for the automatic reciprocate link from Digital Bodleian to the catalogue, which is being developed?

**Comment by ahankinson** [comment]
In this instance the link pointed to a page in the middle!

**Comment by ahankinson** [comment]
But yes, it does make a difference.if the UUID in the link record doesn’t match the UUID of the object, no link will be shown

**Comment by ahankinson** [comment]
I usually find it by clicking the IIIF icon... the UUID in the url is always the object ID.

**Pull request merged**
