### PR TITLE
retro-conversion

### PR DESCRIPTION
**Pull request by sjabrookes**

### CODE REVIEW

**Comment by sjabrookes** [comment]
That’s weird. It says I’m up-to-date.

Best, Stewart
--


On 5 May 2023, at 14:01, Andrew Dunning ***@***.******@***.***>> wrote:



Could you please try updating your branch? It looks as if you are working from an old version.

**Comment by adunning** [comment]
I was wondering why the checks were not running; fixed now.

**Comment by holfordm** [comment]
The entity check fails because of how @sjabrookes marks up person names which lack current entries in the authority files (person_???). @sjabrookes -- to avoid this happening, just mark those names up with persName elements _without keys_ :`<persName>John Smith</persName>` rather than `<persName key="person_???">John Smith</persName>`. The elements without keys will still be flagged so I will still see them.
@adunning please could you respond to #688 regarding workflow around these automated checks.

**Comment by holfordm** [comment]
@sjabrookes additionally if there is a person who needs a new VIAF entry, again just leave the persName element without a key to avoid errors. You can use an xml comment to record the viaf id or email me with the details.

**Comment by adunning** [comment]
If you provide a URL for an external entity in `@ref` that will also still validate:

```xml
<persName ref="https://viaf.org/viaf/121756032/">Matthew Holford</persName>
```

My scheme is to have a script that will automatically create new authority records for these and replace `@ref` with `@key`.

**Comment by adunning** [comment]
The checks are finally working properly; thanks for your patience!

**Comment by sjabrookes** [comment]
Okay, will do! Thanks!

Best,

Stewart

**Comment by sjabrookes** [comment]
Okay, great, that’s my new directive. 

Best, Stewart

**Comment by sjabrookes** [comment]
That sounds very clever! Looking forward ;-)

**Comment by holfordm** [comment]
(ps, just ignore Andrew’s comments about adding a ref element. Have a good weekend!)

**Pull request merged**
