### PR TITLE
Update preview.css

### PR DESCRIPTION
**Pull request by holfordm**
this change adds padding and a border under msSummary ("Summary of Contents"), which I think improves legibility - if you agree can a similar change be made to the CSS on the main website?

### CODE REVIEW

**Review by clairedaywork — COMMENTED** [review]
I can't find an example where msSummary is used to see the change. Would it be possible to add before/after screenshots or link to a page example, please?
I tested the change on the main website code locally (Georgian version) and agree it looks better.

**Comment by holfordm** [comment]
@clairedaywork for example: https://medieval.bodleian.ox.ac.uk/catalog/manuscript_66 or https://medieval.bodleian.ox.ac.uk/catalog/manuscript_1380 
there are other cases (e.g. https://medieval.bodleian.ox.ac.uk/catalog/manuscript_1167 or https://medieval.bodleian.ox.ac.uk/catalog/manuscript_1615 ) where the "Summary" is followed directly by the "Physical description" - in these cases the current CSS looks fine, and the proposed change would introduce a line between contents and physical description that isn't usually present - so perhaps the CSS rule needs to be more complicated than what I have suggested.

**Review by clairedaywork — COMMENTED** [review]
@holfordm Thank you for the links.  I think the change adds a good visual separation.  Are you happy with the cases where 'Languages(s)' (being part of the Contents) follows the summary and precedes Physical Description?

**Comment by holfordm** [comment]
@clairedaywork Yes, happy with those

**Review by clairedaywork — APPROVED** [review]

**Pull request merged**
