### PR TITLE
Final provenance and acquisition added to Lyell collection

### PR DESCRIPTION
**Pull request by littlegustv**

### CODE REVIEW

**Comment by andrew-morrison** [comment]
[MS_Lyell_88.xml](https://github.com/littlegustv/medieval-mss/commit/40a132457082b9306ddee65c30085c2c58d185f3#diff-86) is invalid due to the addition of a `provenance` element after an `acquisition` element, and then another `acquisition` following that. The TEI P5 schema requires `history` elements contain the following:

1. A single `summary` element
2. A single `origin` element
3. Multiple `provenance` elements
4. Finally, a single `acquisition` element

All are optional but if they occur they must be in that order.

In this case, it appears the information added is superfluous. But @holfordm is the person to review for content. Possibly whatever script you are using should skip any files already containing an `acquisition` element?

**Comment by holfordm** [comment]
Hi @littlegustv , thanks for your work on this! @andrew-morrison  is right - some of the records (in Lyell and other named collections) already contain acquisition and/or provenance elements. These records should be skipped by the script, but it would be useful if the script could check whether Lyell's ID is contained in the record, since some records (e.g. MS. Lyell 8) have medieval provenance information but nothing later than that.
Also, the `provenance `and `acquisition `elements should go inside `history `(after `origin`), not after `history`.

**Comment by holfordm** [comment]
Sorry, a couple of other things:
- the text of the elements to be added has been revised in the Google sheet and now reads: `<provenance notBefore="1871" notAfter="1948"><persName role="formerOwner" key="person_64157046">James P. R. Lyell, 1871-1948</provenance><acquisition when="1948">Chosen as one of the hundred manuscripts bequeathed to the Bodleian by Lyell in 1948.</acquisition>`
- did @andrew-morrison or Mitch Fraas (sorry don't know his handle if he has one) or @littlegustv  have any thoughts about documenting this change in the TEI, e.g. with a `change` in `revisionDesc`?

**Comment by andrew-morrison** [comment]
@holfordm wrote:
> Also, the provenance and acquisition elements should go inside history (after origin), not after history.

They _are_ inside the history. It just looks like they've been inserted after the `</history>` tag, because additions are all on one line, and diffs are displayed on a line-by-line basis. That always catches me out too. If you open them in Oxygen and use the Format and Indent tool it becomes clearer.

**Comment by andrew-morrison** [comment]
@holfordm wrote:
> did @andrew-morrison or Mitch Fraas (sorry don't know his handle if he has one) or @littlegustv have any thoughts about documenting this change in the TEI, e.g. with a change in revisionDesc?

If you want to add a `change` in the `revisionDesc` just make sure it is inserted as first child and has a `@when` attribute. Optionally, you can give it an `@xml:id` attribute then reference that using a `@change` attribute added to the element(s) you insert elsewhere in the document. But we don't do anything with those on the web site (it would get very cluttered if everything had a footnote saying who added what.)

BTW, I believe Mitch Fraas's handle is @amfraas.

**Comment by littlegustv** [comment]
Ok, I should have a new attempt later today.  I can definitely add a change tag as well, but I am not entirely sure what it needs to say!  What is the TEI expectation for this?

**Comment by ahankinson** [comment]
Hi @littlegustv -- Thanks for your submissions! I just wanted to chime in on the mechanics of the pull requests.

If you create a dedicated branch on your fork -- let's call it 'add-lyell-provenence' -- and make all your changes on that branch instead of your 'master', then you can open a pull request that will request to merge from `littlegustv:add-lyell-provenance` to `medieval-mss:master`. 

When you do that, you can keep the pull request open. You don't need to keep opening and closing the pull requests when you make a mistake. It's easier for us (and you!) to keep track of the suggested changes if we don't have to hunt back through previous conversations to see what's requested.

**Comment by littlegustv** [comment]
Ok, that makes more sense!  There is now a new pull request from a new branch, so hopefully if anything goes wrong I can make changes less disruptively.

Thanks for bearing with me as I try to figure this out!

**Pull request closed without merging**
