### PR TITLE
Reindent Radcliffe Trust MSS

### PR DESCRIPTION
**Pull request by adunning**
This is a simple demonstration of Oxygen's format operation with the project settings I have created. Would you like any changes?

### CODE REVIEW

**Comment by adunning** [comment]
I've added a few more changes to illustrate easy modifications to make the files tidier:

- substituting – instead of - and × in place of x between numbers;
- logical order for notBefore/notAfter and min/max;
- Unicode superscripts in place of extra tags.

**Comment by holfordm** [comment]
One initial comment is that I find the Unicode superscript characters in the collation formulas very difficult to read. Do they meet our accessibility requirements?

**Comment by holfordm** [comment]
Otherwise looks helpful. What do you think @andrew-morrison ?

**Comment by andrew-morrison** [comment]
I've run the indexing script on this branch and loaded the results to the QA server. And I've compared with the results of re-indexing from the master branch (but haven't loaded that to production because there is a missing authority entry, person_24205298). 

Here are a few differences:

- Using `<q>` in summaries instead of quote marks means they aren't distinguished from the rest of the text in the search results (e.g. search for "MS. Radcliffe Trust e. 30").
- In the manuscript pages, those single quote marks are now curly instead of straight.
- Hyphens are replaced with en dashes (you may struggle to get contributors to maintain that standard)
- As mentioned above, the superscript. I cannot make those any bigger, relative to the rest of the text, unless you change them to use `<hi rend="superscript">`, and even then they'd start to overlap the line of text above (in Firefox, other browser may change the line spacing). Users can increase their font size, and everything will get bigger in proportion.

There are space differences but they look insignificant and should be ignored by web browsers. But check yourself by comparing the same Radcliffe records on QA and production.

**Comment by holfordm** [comment]
Thanks @andrew-morrison 
The first issue (summaries) we can address by not turning '..' to `<q>` in `<title>` elements. This would be good anyway I think as it is not usually semantically appropriate. We could convert to printer's apostrophes instead of straight apostrophes if desired.
The legibility of the unicode superscript continues to be a problem for me. I don't think users should have to adjust font size to make the page legible. Is there an advantage to using these characters (rather than `<hi=superscript>` that I'm missing?

**Comment by adunning** [comment]
After discussion I'm going to run indentation only on the entire repository and leave other aesthetic changes for later.

**Pull request closed without merging**
