### PR TITLE
MS. Bodl. 764: new description

### PR DESCRIPTION
**Pull request by adunning**

### CODE REVIEW

**Comment by adunning** [comment]
@holfordm Your [MS. Ashmole 1511](https://medieval.bodleian.ox.ac.uk/catalog/manuscript_290) gives both rubrics within `<msItem>` and a list of illustrations. Irritatingly there are no rubrics to give an easy guide to the Latin, but do you think we need the incipits of each section to serve a similar function?

**Comment by holfordm** [comment]
I think it is probably useful to give a chapter by chapter breakdown with reference to Clark's edition, since one of the common questions about the manuscript is "where can I find a translation of this section"

**Comment by adunning** [comment]
You can now see how I've done this up to fol. 31r – let me know if you have any suggestions. It's tempting to systematically identify the extended passages as well (quotations from Isidore, Rabanus Maurus, etc.) but that is probably going beyond our remit …

**Comment by holfordm** [comment]
I think what you've done so far looks good If the extracts are all coming from the same few texts I suppose these could be lsited at the beginning, as you have already started to do.

**Comment by adunning** [comment]
Closer inspection shows that the summary of sources given in Clark is inaccurate, so I will need to go through it systematically.

**Pull request merged**
