### PR TITLE
Fixed: Remove extra commas

### PR DESCRIPTION
**Pull request by ahankinson**
Removes an extra comma in Barocci 214 description.

### CODE REVIEW

**Comment by ahankinson** [comment]
I'm not sure why it's showing the greek has changed -- I didn't touch that. Perhaps it's a problem with editing via the GH web interface?

**Comment by andrew-morrison** [comment]
Did you use the edit in the GitHub web interface? That can change character encodings. It can make a mess of Arabic. But in this case you can only see the different in HEX:
```
echo "πατέραν" | hexdump
0000000 80cf b1ce 84cf bde1 cfb3 ce81 ceb1 0abd
0000010
echo "πατέραν" | hexdump
0000000 80cf b1ce 84cf adce 81cf b1ce bdce 000a
000000f
```

**Comment by ahankinson** [comment]
Yeah, I did.

**Comment by andrew-morrison** [comment]
Also GitHub is saying, "This pull request is closed, but the fixed-barocci-214 branch has unmerged commits." Not sure what that means.

**Comment by ahankinson** [comment]
I closed the PR since it was introducing changes that may not have been desired. If you want to push the change in, it's on Line 158

**Comment by andrew-morrison** [comment]
Funny, my GitKraken client was showing it as merged. It is fixed now.

**Comment by ahankinson** [comment]
thank you!

**Pull request closed without merging**
