### PR TITLE
new descriptions, Merton College MSS 138-140

### PR DESCRIPTION
**Pull request by tainonen**

### CODE REVIEW

**Comment by holfordm** [comment]
Tuija

I have merged this request but for some reason it hasn't come through online (conflict in Merton MS. 14 still shows as unresolved).. Please could you close this request. 

Thanks 
Matthew

**Comment by tainonen** [comment]
closing this as requested by MH

**Comment by tainonen** [comment]
hi Matthew,

I've attempted to close this now - hopefully I succeeded.

Tuija

**Comment by andrew-morrison** [comment]
These sort of problem might be avoided, or be less likely, if you start a new branch on your fork whenever you start a batch of work. Then submit the pull request and, if you want to continue working while Matthew reviews it, start another branch on your fork.

Working on the _tainonen:master_, as you have been, means your update of MS. 134 committed on the 12th was added to this pull request, and conflicted with a change Matthew made to the same record on the 11th, on _bodleian:master_.

**Pull request closed without merging**
