### PR TITLE
new records for Brasenose, LMH

### PR DESCRIPTION
**Pull request by holfordm**

### CODE REVIEW

**Comment by holfordm** [comment]
Dear @andrew-morrison - these are records for two college collections on deposit and the Bodleian (and therefore orderable via Aeon) EXCEPT for 5 Brasenose manuscripts still at the college, which have `availability` marked as `none`.  They all need to have relevant ARKs added - can this be done en masse? Let me know if there are any other changes I should make.
(I'm aware of a couple of missing `@keys` and that the provenance sections aren't fully marked up - I will come back to those sections when I have more time)

**Comment by andrew-morrison** [comment]
I have re-indexed the QA server, if you wish to make any visual checks.

To give the records belonging to these new colleges request buttons requires deploying changes to the server. Do you want them published today, or would you prefer to wait until they get request buttons?

Minting of new ARKs are being arranged by @irv and @ajrhitchman.

**Comment by ajrhitchman** [comment]
@irv has added brasenose and lmh to the [ark minter](https://pii.bodleian.ox.ac.uk/static/mint.html), and i've run through and added them en masse as requested.

**Comment by holfordm** [comment]
@andrew-morrison many thanks - probably makes sense to wait for indexing until request buttons are available

**Comment by holfordm** [comment]
@Slange-Mhath Andrew said you might be making the server changes mentioned - if that's right feel free to merge this into master at the appropriate moment

**Comment by holfordm** [comment]
@Slange-Mhath - any update on the server changes?

**Comment by Slange-Mhath** [comment]
> @Slange-Mhath - any update on the server changes?

Hey Matthew, sorry we decided to hold off with that until the new year because there was just a small time window in which we could have fitted it in before the christmas break and also to then do an update which includes the other -hopefully by then - implemented changes! It is on my radar :)

**Comment by holfordm** [comment]
Thanks Seb! Have a great Christmas if we don't speak before...

**Comment by holfordm** [comment]
@Slange-Mhath apologies for bothering you with something else but it would be great to have this done before you leave!

**Pull request merged**
